version: 2.1

# Jobs to run
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
         name: Install npm dependencies
         command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
        # Build the Docker image
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            docker build -t nodeapp:latest .
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push nelsonosagie/nodeapp:latest

      # Push the Docker image to a Docker registry (replace with your own registry)
      - run:
          name: Push Docker Image
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push nelsonosagie/nodeapp:latest

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_test
      - build_docker_image